### ISSUE TITLE
SIGSEGV in ofURLFileLoader::handleRequest(ofHttpRequest) on ODROID-U3/Xubuntu 13.10

### ISSUE THREAD

**Issue by pizthewiz** [openframeworks/openFrameworks#2823]
Split out from the forum discussion thread [Issue in ofxTwitter addon on armv7 (Odroid U3)](http://forum.openframeworks.cc/t/issue-in-ofxtwitter-addon-on-armv7-odroid-u3/14754/9?u=pizthewiz), it appears as though all examples that make use of `ofURLFileLoader::handleRequest(ofHttpRequest)` blow up on the [ODROID-U3](http://hardkernel.com/main/products/prdt_info.php) with both oF v0.8.0 and on the master branch.

Initially it was thought to be an issue with *ofxJSON* (I am using @bakercp's [fork](https://github.com/bakercp/ofxJSON)) but in fact, all but one of the addon's examples use `ofURLFileLoader::handleRequest(ofHttpRequest)` while the one that does not, does not  crash.

The issue easily reproduces with *threadedImageLoaderExample*:
![gdb session of threadedImageLoaderExample](http://forum.openframeworks.cc/uploads/default/3382/c05e4551f2885102.png)

gdb session:
```
(gdb) r
Starting program: /home/odroid/sandbox/openFrameworks/openFrameworks/examples/addons/threadedImageLoaderExample/bin/threadedImageLoaderExample 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0xb6eb43c8 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) c
Continuing.
Cannot access memory at address 0x0
[New Thread 0xb6418300 (LWP 13510)]
[New Thread 0xb5c18300 (LWP 13511)]
[New Thread 0xb4eff300 (LWP 13512)]
[New Thread 0xb44ff300 (LWP 13513)]
[verbose] ofURLFileLoader: threadedFunction(): starting thread
[verbose] ofURLFileLoader: threadedFunction(): querying request image2
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition
[verbose] ofURLFileLoader: start(): signaling new request condition

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb44ff300 (LWP 13513)]
0xb6a861f8 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
(gdb) bt
#0  0xb6a861f8 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#1  0x0007ae1c in ofURLFileLoader::handleRequest(ofHttpRequest) ()
#2  0x0007b436 in ofURLFileLoader::threadedFunction() ()
#3  0x000785c4 in ofThread::run() ()
#4  0x000dbd58 in Poco::ThreadImpl::runnableEntry(void*) ()
#5  0xb6b4ee64 in start_thread (arg=0xb44ff300) at pthread_create.c:313
#6  0xb691dc28 in ?? ()
    at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:96
   from /lib/arm-linux-gnueabihf/libc.so.6
#7  0xb691dc28 in ?? ()
    at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:96
   from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by pizthewiz** [comment]
The apothecary formula for Poco 1.6 has been merged in PR #3448.

**Comment by bilderbuchi** [comment]
so, can this be closed, @pizthewiz ?

**Comment by pizthewiz** [comment]
Yeah I think it can, I was just waiting to test it before closing.

**Comment by bilderbuchi** [comment]
ok, then i'll leave the closing to you.
