### ISSUE TITLE
make failed with exit status 2

### ISSUE THREAD

**Issue by MIRIK1297** [openframeworks/openFrameworks#5456]
Hello, I'm new with OF and I followed the instruction: http://openframeworks.cc/setup/android-studio/
But when I try to build any example I have problem Error:(157, 0) Cause: make failed with exit status 2
My configuration: Win 7, AS 2.2,3, of_v0.9.8_android_release
Logs:

> 2017-02-22 12:10:23,365 [5809476]   INFO - .BaseProjectImportErrorHandler - Failed to import Gradle project at 'C:\Work\openFrameworks\of_v0.9.8_android_release\examples\android\androidEmptyExample' 
org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(DefaultBuildActionExecuter.java:48)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.doResolveProjectInfo(GradleProjectResolver.java:217)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.access$300(GradleProjectResolver.java:73)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:768)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:752)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:238)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:112)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:73)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file 'C:\Work\openFrameworks\of_v0.9.8_android_release\libs\openFrameworksCompiled\project\android\build.gradle' line: 157
A problem occurred evaluating project ':openFrameworksProject'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:77)
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:108)
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:97)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.configure(InProcessBuildActionExecuter.java:84)
	at org.gradle.tooling.internal.provider.ClientProvidedBuildAction.run(ClientProvidedBuildAction.java:43)
	at org.gradle.tooling.internal.provider.ClientProvidedBuildAction.run(ClientProvidedBuildAction.java:31)
	at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating project ':openFrameworksProject'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	... 32 more
Caused by: org.gradle.api.GradleException: make failed with exit status 2
	at build_6g2vigoiwbkesm82twuq9jy0i.ofRunMake(C:\Work\openFrameworks\of_v0.9.8_android_release\libs\openFrameworksCompiled\project\android\build.gradle:157)
	at build_6g2vigoiwbkesm82twuq9jy0i$_run_closure3.doCall(C:\Work\openFrameworks\of_v0.9.8_android_release\libs\openFrameworksCompiled\project\android\build.gradle:162)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:482)
	at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:863)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_6g2vigoiwbkesm82twuq9jy0i.run(C:\Work\openFrameworks\of_v0.9.8_android_release\libs\openFrameworksCompiled\project\android\build.gradle:161)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 43 more
2017-02-22 12:10:23,368 [5809479]   WARN - nal.AbstractExternalSystemTask - Cause: make failed with exit status 2 
com.intellij.openapi.externalSystem.model.LocationAwareExternalSystemException: Cause: make failed with exit status 2
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:103)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:158)
	at org.jetbrains.plugins.gradle.service.project.BaseGradleProjectResolverExtension.getUserFriendlyError(BaseGradleProjectResolverExtension.java:579)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:158)
	at com.android.tools.idea.gradle.project.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:405)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:772)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:752)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:238)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:112)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:73)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-02-22 12:10:23,368 [5809479]   WARN - radle.project.ProjectSetUpTask -  
2017-02-22 12:10:23,369 [5809480]   INFO - radle.project.ProjectSetUpTask - Cause: make failed with exit status 2

Consult IDE log for more details (Help | Show Log) 
2017-02-22 12:10:23,369 [5809480]   INFO - ls.idea.gradle.GradleSyncState - Sync with Gradle for project 'androidEmptyExample' failed: Cause: make failed with exit status 2

Consult IDE log for more details (Help | Show Log) 
2017-02-22 12:10:23,481 [5809592]   INFO -       #com.jetbrains.cidr.lang - Clearing symbols finished in 0 s. 
2017-02-22 12:10:23,488 [5809599]   INFO -       #com.jetbrains.cidr.lang - Loading symbols finished in 0 s. 
2017-02-22 12:10:23,495 [5809606]   INFO -       #com.jetbrains.cidr.lang - Building symbols finished in 0 s. 
2017-02-22 12:10:23,495 [5809606]   INFO -       #com.jetbrains.cidr.lang - Saving symbols finished in 0 s.

**Comment by MIRIK1297** [comment]
Same result I have with eclipse:

> 17:55:33 **** Build of configuration Android for project openFrameworks ****
make -j4 all PLATFORM_OS=Android 
HOST_OS=MINGW32_NT-6.1
HOST_OS=MINGW32_NT-6.1
HOST_OS=MINGW32_NT-6.1
Compiling /c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/3d/of3dPrimitives.cpp
/Work/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/arm-linux-androideabi-g++ -O0 -g3 -DANDROID_NDK -D_DEBUG -DDEBUG  -Wall -std=c++14 -nostdlib --sysroot=/Work/android-ndk-r10e/platforms/android-19/arch-arm/ -fno-short-enums -ffunction-sections -fdata-sections -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID -I"/Work/android-ndk-r10e/platforms/android-19/arch-arm//usr/include/" -I"/Work/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/include" -I"/Work/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include" -I"/Work/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include" -I"/Work/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include" -I"/Work/android-ndk-r10e/sources/crystax/include/" -I"/c/Work/openFrameworks/of_v0.9.8_android_release/libs/glu/include_android" -I"/c/Work/openFrameworks/of_v0.9.8_android_release/addons/ofxAndroid/src" -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/FreeImage/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/boost/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/boost/include/boost -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/freetype/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/freetype/include/freetype2 -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/freetype/include/freetype2/config -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/freetype/include/freetype2/internal -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/freetype/include/freetype2/internal/services -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/glfw/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/glfw/include/GLFW -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openssl/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openssl/include/openssl -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/poco/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/tess2/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/utf8cpp/include -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/utf8cpp/include/utf8 -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/3d -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/app -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/communication -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/events -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/gl -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/graphics -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/math -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/sound -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/types -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/utils -I/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/video -DDEBUG  -MMD -MP -MF /c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworksCompiled/lib/android/obj/armv7/Debug/libs/openFrameworks/3d/of3dPrimitives.d -MT/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworksCompiled/lib/android/obj/armv7/Debug/libs/openFrameworks/3d/of3dPrimitives.o -o /c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworksCompiled/lib/android/obj/armv7/Debug/libs/openFrameworks/3d/of3dPrimitives.o -c /c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworks/3d/of3dPrimitives.cpp
/bin/sh: /Work/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/arm-linux-androideabi-g++: No such file or directory
make[2]: *** [/c/Work/openFrameworks/of_v0.9.8_android_release/libs/openFrameworksCompiled/lib/android/obj/armv7/Debug/libs/openFrameworks/3d/of3dPrimitives.o] Error 127
make[1]: *** [Debug] Error 2
make: *** [all] Error 2
make: INTERNAL: Exiting with 5 jobserver tokens available; should be 4!

17:56:03 Build Finished (took 30s.270ms)

**Comment by arturoc** [comment]
do you have the android NDK installed at `/Work/android-ndk-r10e/`?

**Comment by MIRIK1297** [comment]
I just unpacked it in /Work
Am I right?
![1](https://cloud.githubusercontent.com/assets/15186589/23217467/5b60c360-f92a-11e6-9a3a-84509c745e07.jpg)

**Comment by arturoc** [comment]
which path do you have in the paths.make file? seems like you've set it up as a unix path but you are on windows.

**Comment by MIRIK1297** [comment]
You are right, my fault. But now another problem with studio: "Gradle: Configure project:openFrameworksProject" - it seems that this will not end (7 hours not enough).
Can you help me with this?

**Comment by razvanilin** [comment]
I was just trying to get it working too and it hangs on the same process.
