### ISSUE TITLE
Android Crashes when using GLES Version 2 (master)

### ISSUE THREAD

**Issue by kkirby** [openframeworks/openFrameworks#5457]
Hello,

I just pulled master and tried to get a basic camera working with GLES 2. The app crashes. I know this was an issue once before but I'm confident it was fixed.

It's reproducible by updating the main.cpp in the `androidCameraExample` project:

```c++
int main(){
	ofGLESWindowSettings settings;
	settings.setGLESVersion(2);
	ofCreateWindow(settings);

	// this kicks off the running of my app
	// can be OF_WINDOW or OF_FULLSCREEN
	// pass in width and height too:
	ofRunApp( new ofApp() );
	return 0;
}
```

I'm running a Nexus 5X with Pure Nexus 6.0.1-20160723 (Android 6.0.1)

I've attached the ADB log.

[adb.log.txt](https://github.com/openframeworks/openFrameworks/files/794785/adb.log.txt)

**Comment by kkirby** [comment]
It's apparently unrelated to the camera. My bad. Here's the stack trace:

```
#0  0xea75ec4e in glCreateProgram () from /Users/kkirbatski/.android/device_libs/0bb1238ef74b856886f07e037074f7d9/libs/system/lib/lib/libGLESv2_enc.so
#1  0xe2c0222a in ofShader::checkAndCreateProgram (this=0xee889120) at /Users/kkirbatski/Projects/openFrameworks/libs/openFrameworks/gl/ofShader.cpp:635
#2  0xe2bfcda4 in ofShader::setupShaderFromSource(ofShader::Source&&) (this=0xee889120,
    source=<unknown type in /Users/kkirbatski/Projects/openFrameworks/apps/devApps/androidCameraExample/libs/x86/libOFAndroidApp_x86.so, CU 0x775658, DIE 0x80f44c>)
    at /Users/kkirbatski/Projects/openFrameworks/libs/openFrameworks/gl/ofShader.cpp:326
#3  0xe2c0193f in ofShader::setupShaderFromSource (this=0xee889120, type=35633, source=..., sourceDirectoryPath=...) at /Users/kkirbatski/Projects/openFrameworks/libs/openFrameworks/gl/ofShader.cpp:317
#4  0xe2bd1a41 in ofGLProgrammableRenderer::setup (this=0xee887c10, _major=2, _minor=0) at /Users/kkirbatski/Projects/openFrameworks/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp:2426
#5  0xe2abecba in Java_cc_openframeworks_OFAndroid_onSurfaceCreated (env=0xeae35940, thiz=0xe288d5ac) at /Users/kkirbatski/Projects/openFrameworks/addons/ofxAndroid/src/ofAppAndroidWindow.cpp:326
#6  0xee9570ef in ?? ()
```
