### ISSUE TITLE
particleExample runtime error: integer overflow (Compiled for WebAssembly)

### ISSUE THREAD

**Issue by Enellis** [openframeworks/openFrameworks#5702]
Hey,

many examples and all my own projects run perfectly when compiled for WebAssembly but in some example projects e.g "particleExample" I get this exception:

Chrome:
`exception thrown: RuntimeError: integer result unrepresentable`

Firefox:
`exception thrown: RuntimeError: integer overflow,wasm-function`

Seems like Unity had the same problem but somehow they managed to fix it: https://forum.unity3d.com/threads/integer-overflow-integer.468203/

**Comment by cuinjune** [comment]
Hi, I'm sorry this is not an answer to you question but do you mind sharing the process of compiling OF to WebAssembly? Was it an easy job for you? Thanks in advance!

**Comment by Enellis** [comment]
@cuinjune Actually, it is very easy. As I said, you just have to add `PROJECT_LDFLAGS=-s WASM=1` to the config.make file in the project directory and then execute `emmake make`

**Comment by cuinjune** [comment]
@Enellis Thanks for your answer.
I just tried it with an emptyExample in OF/examples folder.
But I got the following error..

<img width="1439" alt="screen shot 2017-07-25 at 12 02 34 am" src="https://user-images.githubusercontent.com/24947986/28529916-e39d5490-70cc-11e7-94ff-9262d3ce63ac.png">

In terminal,

> [4690:37379:0725/000222.544836:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
> failed to asynchronously prepare wasm: LinkError: Import #4 module="env" function="__ZNSt3__15ctypeIcE2idE" error: global import must be a number
> LinkError: Import #4 module="env" function="__ZNSt3__15ctypeIcE2idE" error: global import must be a number
> LinkError: Import #4 module="env" function="__ZNSt3__15ctypeIcE2idE" error: global import must be a number

I added `PROJECT_LDFLAGS=-s WASM=1` flag on the bottom of config.make and I compiled it by `emmake make`. and then I tried to open it on Chrome by `emrun --browser chrome bin/emptyExample.html`. Did I do something wrong? Could you give me an advice on how to fix this?

**Comment by Enellis** [comment]
Wierd. It should work exactly the way you did it. Do you have the latest emsdk?

**Comment by cuinjune** [comment]
Yes I just downloaded installed one today. I will try with other example.

**Comment by edap** [comment]
@Enellis could you share your config.make file, or be a little more detailed about how did you add these flags? I've added at the end of the file and I've got this error:

```
Traceback (most recent call last):
  File "/Users/me/emsdk_portable/emscripten/tag-1.34.12/emcc", line 1309, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/Users/me/emsdk_portable/emscripten/tag-1.34.12/tools/shared.py", line 1426, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
make[1]: *** [bin/3DPrimitivesExample.html] Error 1
make: *** [Release] Error 2
```

Also adding the flags keeping the default, like: 
`PROJECT_LDFLAGS=-Wl,-rpath=./libs, -s WASM=1`
is generating an error.

I'm testing the example `3d/3DPrimitivesExample`, with the last master. Which example and OF version are you using?

**Comment by Enellis** [comment]
@edap 
I'm using OF version 0.9.8 and the 3DPrimitivesExample compiles fine.
I really just add ```PROJECT_LDFLAGS=-s WASM=1``` after this line: ```# PROJECT_LDFLAGS=-Wl,-rpath=./libs```

My emsdk configuration:
```
     *     clang-e1.37.16-64bit     	INSTALLED
     *     node-4.1.1-64bit         	INSTALLED
     *     emscripten-1.37.16       	INSTALLED
     *     sdk-1.37.16-64bit        	INSTALLED

**Comment by chuckleplant** [comment]
I tried building 3DPrimitivesExample with WASM and failed with: 

```
Assertion failed: (mappedFunctions.count(name)), function getFunctionIndex, file /Users/clb/emslave/buildslave/osx-tagbuilder/emsdk/binaryen/tag-1.37.9/src/wasm/wasm-binary.cpp, line 320.
Traceback (most recent call last):
  File "/Users/sergio-mb/Applications/emsdk-portable/emscripten/1.37.9/em++", line 16, in <module>
    emcc.run()
  File "/Users/sergio-mb/Applications/emsdk-portable/emscripten/1.37.9/emcc.py", line 2170, in run
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/Users/sergio-mb/Applications/emsdk-portable/clang/e1.37.9_64bit/binaryen/bin/asm2wasm', 'bin/3DPrimitivesExample.temp.asm.js', '--total-memory=134217728', '--emit-jsified-potential-traps', '-O3', '--mem-init=bin/3DPrimitivesExample.html.mem', '--mem-base=1024', '-o', 'bin/3DPrimitivesExample.wasm']' returned non-zero exit status -6
make[1]: *** [bin/3DPrimitivesExample.html] Error 1
make: *** [Release] Error 2
```

OF: 39b6731012f
emscripten-1.37.9
