### ISSUE TITLE
Emscripten 3DPrimitivesExample make error

### ISSUE THREAD

**Issue by kubmin** [openframeworks/openFrameworks#5787]
Hi there,

When building the 3DPrimitivesExample with emscripten I get this error, but I'm not quite sure what's happening. I'm running the following commands after follwing this guide on how to install emscripten: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

`cd Developer/openFrameworks_v0.9.8/examples/3d/3DPrimitivesExample/`
`emmake make`

which gives the follwing error:

```
`lazy` symbol binding failed: Symbol not found: _futimens
  Referenced from: /Users/megatrends/Developer/emsdk/clang/e1.37.22_64bit/llvm-ar
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _futimens
  Referenced from: /Users/megatrends/Developer/emsdk/clang/e1.37.22_64bit/llvm-ar
  Expected in: /usr/lib/libSystem.B.dylib

0  llvm-ar                  0x0000000109217d88 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  llvm-ar                  0x0000000109218336 SignalHandler(int) + 358
2  libsystem_platform.dylib 0x00007fff94804b3a _sigtramp + 26
3  libsystem_platform.dylib 0x0000000111639b4d _sigtramp + 2095271981
4  libsystem_platform.dylib 0x0000000111644464 _sigtramp + 2095315268
5  libsystem_platform.dylib 0x000000011161f793 _sigtramp + 2095164531
6  libsystem_platform.dylib 0x000000011161f89e _sigtramp + 2095164798
7  libdyld.dylib            0x00007fff945f1282 dyld_stub_binder + 282
8  llvm-ar                  0x000000010944e340 (anonymous namespace)::DarwinX86AsmBackend::getCompactUnwindRegNum(unsigned int) const::CU64BitRegs + 10650
9  llvm-ar                  0x00000001090dfe6d performOperation(ArchiveOperation, llvm::object::Archive*, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 2013
10 llvm-ar                  0x00000001090df0a2 performOperation(ArchiveOperation, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 930
11 llvm-ar                  0x00000001090dcc99 main + 361
12 libdyld.dylib            0x00007fff945f5235 start + 1
Stack dump:
0.	Program arguments: /Users/megatrends/Developer/emsdk/clang/e1.37.22_64bit/llvm-ar xo /Users/megatrends/Developer/openFrameworks_v0.9.8/libs/FreeImage/lib/emscripten/libfreeimage.a 

extract archive contents(/Users/megatrends/.emscripten_cache/asmjs/libcxx_noexcept.a) failed with error: llvm-ar failed to extract file(s) ['/private/tmp/emscripten_temp_TohiMM_archive_contents/any_7924d0da.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/bind_f02ebcc5.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/chrono_f2615c08.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/condition_variable_ae54bdd6.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/debug_2a51bb88.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/exception_cf7063eb.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/future_6390d701.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/hash_38663e05.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/ios_4ee3e9e1.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/iostream_199bd113.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/locale_91ebb176.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/memory_21eb2d5b.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/mutex_b8f7bcd0.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/new_038a4243.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/optional_0345d8c4.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/random_66626863.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/regex_f0ce51b2.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/shared_mutex_b634ba25.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/stdexcept_2577ab21.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/string_f184f8e7.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/strstream_35c97b30.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/system_error_1c0d85bf.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/thread_1b9e9ecc.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/typeinfo_e69326dc.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/utility_c2662133.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/valarray_d378b1bd.cpp.o', '/private/tmp/emscripten_temp_TohiMM_archive_contents/variant_2e049178.cpp.o'] from archive file /Users/megatrends/.emscripten_cache/asmjs/libcxx_noexcept.a! Error:dyld: lazy symbol binding failed: Symbol not found: _futimens
  Referenced from: /Users/megatrends/Developer/emsdk/clang/e1.37.22_64bit/llvm-ar
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _futimens
  Referenced from: /Users/megatrends/Developer/emsdk/clang/e1.37.22_64bit/llvm-ar
  Expected in: /usr/lib/libSystem.B.dylib

0  llvm-ar                  0x0000000106f50d88 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  llvm-ar                  0x0000000106f51336 SignalHandler(int) + 358
2  libsystem_platform.dylib 0x00007fff94804b3a _sigtramp + 26
3  libsystem_platform.dylib 0x0000000113c3ab4d _sigtramp + 2135121965
4  libsystem_platform.dylib 0x0000000113c45464 _sigtramp + 2135165252
5  libsystem_platform.dylib 0x0000000113c20793 _sigtramp + 2135014515
6  libsystem_platform.dylib 0x0000000113c2089e _sigtramp + 2135014782
7  libdyld.dylib            0x00007fff945f1282 dyld_stub_binder + 282
8  llvm-ar                  0x0000000107187340 (anonymous namespace)::DarwinX86AsmBackend::getCompactUnwindRegNum(unsigned int) const::CU64BitRegs + 10650
9  llvm-ar                  0x0000000106e18e6d performOperation(ArchiveOperation, llvm::object::Archive*, std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 2013
10 llvm-ar                  0x0000000106e180a2 performOperation(ArchiveOperation, std::__1::vector<llvm::NewArchiveMember, std::__1::allocator<llvm::NewArchiveMember> >*) + 930
11 llvm-ar                  0x0000000106e15c99 main + 361
12 libdyld.dylib            0x00007fff945f5235 start + 1
13 libdyld.dylib            0x0000000000000003 start + 1805692367
Stack dump:
0.	Program arguments: /Users/megatrends/Developer/emsdk/clang/e1.37.22_64bit/llvm-ar xo /Users/megatrends/.emscripten_cache/asmjs/libcxx_noexcept.a 

Traceback (most recent call last):
  File "/Users/megatrends/Developer/emsdk/emscripten/1.37.22/em++", line 16, in <module>
    emcc.run()
  File "/Users/megatrends/Developer/emsdk/emscripten/1.37.22/emcc.py", line 1443, in run
    final = shared.Building.link(linker_inputs, DEFAULT_FINAL, force_archive_contents=force_archive_contents, temp_files=misc_temp_files, just_calculate=just_calculate)
  File "/Users/megatrends/Developer/emsdk/emscripten/1.37.22/tools/shared.py", line 1772, in link
    Building.read_link_inputs(filter(lambda x: not x.startswith('-'), files))
  File "/Users/megatrends/Developer/emsdk/emscripten/1.37.22/tools/shared.py", line 1698, in read_link_inputs
    raise Exception('llvm-ar failed on archive ' + archive_names[n] + '!')
Exception: llvm-ar failed on archive Users/megatrends/Developer/openFrameworks_v0.9.8/libs/FreeImage/lib/emscripten/libfreeimage.a!
```

Any ideas? Quite new to Open Frameworks so sorry if I'm being so unexperienced!

**Comment by bethannezink** [comment]
@kubmin Did you get this issue resolved? I am experiencing the same problem right now, and I'd love to know what you did to resolve it.

**Comment by arturoc** [comment]
0.9.8 is not compatible anymore with latest emscripten, you will need to use the nightly builds if you want to use it

**Comment by noiziv5** [comment]
Using v20170714 nightly buid, getting same error:
(...) dyld: Symbol not found: _futimens (...)

**Comment by bethannezink** [comment]
@noiziv5 I resolved the error by removing the emsdk version of llvm-ar and linking my local version à la `ln -s /usr/local/opt/llvm/bin/llvm-ar ~/libraries/emsdk/clang/e1.37.22_64bit/llvm-ar`. (Obviously, you'll need to change the file paths to match your own.)

**Comment by noiziv5** [comment]
@bethannezink Thank you very much! I had to install clang/llvm with homebrew and linking, as you suggested, emsdk version of llvm-ar to the version compiled in my system. NICE!!!!
