### ISSUE TITLE
androidAudioExample not working

### ISSUE THREAD

**Issue by nishimotz** [openframeworks/openFrameworks#5963]
Regarding my comment for #5736, tested with newer nightly build as follows.

Note that androidCameraExample is working as expected, i.e. runtime permission dialog appears and camera works.

## setup

* Windows 10 (1709) x64
* Nexus 5 Android 6.0.1 (via USB)
* of_v20180410_android_release
* of_v20180408_vs2017_nightly (for projectGenerator)

## steps

command prompt

```
set TARGET=android
set NDK_DIR=android-ndk-r15c
set ANDROID_HOME=c:\Android\sdk
set ROOT=c:\work\of_v20180410_android_release
set ANDROID_NDK_HOME=c:\Android\%NDK_DIR%
set PG_CLI=C:\work\of_vs2017\projectGenerator-vs\resources\app\app\projectGenerator.exe

cd of_v20180410_android_release
%PG_CLI% -p"android" -o"." examples\android\androidAudioExample
```

projectGenerator log

```
[notice ] -----------------------------------------------
[notice ] setting OF path to: C:\work\of_v20180410_android_release\.
[notice ] from -o option
[notice ] target platform is: android
[notice ] updating project C:\work\of_v20180410_android_release\examples\android\androidAudioExample
[ error ] ofFile: copyTo(): source file C:\work\of_v20180410_android_release\.\scripts/templates/android\.gitignore does not exist
[ error ] AndroidStudioProject: error copying gitignore template from C:\work\of_v20180410_android_release\.\scripts/templates/android\.gitignore to C:\work\of_v20180410_android_release\examples\android\androidAudioExample\.gitignore
[notice ] parsing addons.make
[notice ] saving addons.make
[notice ] project updated!
[notice ] -----------------------------------------------

1 project updated [notice ] in -113348 seconds
```

build

```
cd examples\android\androidAudioExample
gradlew installArm7Debug --info
adb logcat "*:e" "OF:*"
```

start the app on device

logcat outputs

```
04-10 23:17:44.827 21989 21989 I OF      : static init
04-10 23:17:44.827 21989 21989 I OF      : loading x86 library
04-10 23:17:44.829 21989 21989 I OF      : failed x86 loading, trying neon detection
04-10 23:17:44.829 21989 21989 I OF      : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cc.openframeworks.androidAudioExample-1/base.apk"],nativeLibraryDirectories=[/data/app/cc.openframeworks.androidAudioExample-1/lib/arm, /data/app/cc.openframeworks.androidAudioExample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libOFAndroidApp_x86.so"
04-10 23:17:44.829 21989 21989 I OF      :      at java.lang.Runtime.loadLibrary(Runtime.java:367)
04-10 23:17:44.829 21989 21989 I OF      :      at java.lang.System.loadLibrary(System.java:1076)
04-10 23:17:44.829 21989 21989 I OF      :      at cc.openframeworks.OFAndroidLifeCycle.<clinit>(OFAndroidLifeCycle.java:24)
04-10 23:17:44.829 21989 21989 I OF      :      at cc.openframeworks.OFActivity.onCreate(OFActivity.java:56)
04-10 23:17:44.829 21989 21989 I OF      :      at cc.openframeworks.androidAudioExample.OFActivity.onCreate(OFActivity.java:13)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.Activity.performCreate(Activity.java:6251)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.ActivityThread.-wrap11(ActivityThread.java)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
04-10 23:17:44.829 21989 21989 I OF      :      at android.os.Handler.dispatchMessage(Handler.java:102)
04-10 23:17:44.829 21989 21989 I OF      :      at android.os.Looper.loop(Looper.java:148)
04-10 23:17:44.829 21989 21989 I OF      :      at android.app.ActivityThread.main(ActivityThread.java:5417)
04-10 23:17:44.829 21989 21989 I OF      :      at java.lang.reflect.Method.invoke(Native Method)
04-10 23:17:44.829 21989 21989 I OF      :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-10 23:17:44.829 21989 21989 I OF      :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-10 23:17:44.830 21989 21989 I OF      : failed neon detection, loading not-neon library
04-10 23:17:44.830 21989 21989 I OF      : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cc.openframeworks.androidAudioExample-1/base.apk"],nativeLibraryDirectories=[/data/app/cc.openframeworks.androidAudioExample-1/lib/arm, /data/app/cc.openframeworks.androidAudioExample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libneondetection.so"
04-10 23:17:44.830 21989 21989 I OF      :      at java.lang.Runtime.loadLibrary(Runtime.java:367)
04-10 23:17:44.830 21989 21989 I OF      :      at java.lang.System.loadLibrary(System.java:1076)
04-10 23:17:44.830 21989 21989 I OF      :      at cc.openframeworks.OFAndroidLifeCycle.<clinit>(OFAndroidLifeCycle.java:30)
04-10 23:17:44.830 21989 21989 I OF      :      at cc.openframeworks.OFActivity.onCreate(OFActivity.java:56)
04-10 23:17:44.830 21989 21989 I OF      :      at cc.openframeworks.androidAudioExample.OFActivity.onCreate(OFActivity.java:13)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.Activity.performCreate(Activity.java:6251)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.ActivityThread.-wrap11(ActivityThread.java)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
04-10 23:17:44.830 21989 21989 I OF      :      at android.os.Handler.dispatchMessage(Handler.java:102)
04-10 23:17:44.830 21989 21989 I OF      :      at android.os.Looper.loop(Looper.java:148)
04-10 23:17:44.830 21989 21989 I OF      :      at android.app.ActivityThread.main(ActivityThread.java:5417)
04-10 23:17:44.830 21989 21989 I OF      :      at java.lang.reflect.Method.invoke(Native Method)
04-10 23:17:44.830 21989 21989 I OF      :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-10 23:17:44.830 21989 21989 I OF      :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-10 23:17:44.839 21989 21989 I OF      : initializing app
04-10 23:17:44.839 21989 21989 I OF      : OFAndroid init...
04-10 23:17:44.840 21989 21989 D OF      : glCreate
04-10 23:17:44.841 21989 21989 D OF      : Create surface
04-10 23:17:44.854 21989 21989 V OF      : trying to find class: cc.openframeworks.androidAudioExample.R$layout
04-10 23:17:44.880 21989 22013 I OF      : Using storage location: /storage/emulated/0
04-10 23:17:44.881 21989 21989 D OF      : glResume
04-10 23:17:44.881 21989 21989 D OF      : addView surface
04-10 23:17:44.886 21989 22013 E         : setup gles1
04-10 23:17:45.085 21989 22017 I OF      : onSurfaceCreated
04-10 23:17:45.091 21989 22017 I OF      : SoundStream setup
04-10 23:17:45.103 21989 22017 I OF      : sound output setup with buffersize: 3544
04-10 23:17:45.109   203   898 E         : Request requires android.permission.RECORD_AUDIO
04-10 23:17:45.109   203   898 E AudioFlinger: openRecord() permission denied: recording not allowed
04-10 23:17:45.109 21989 22017 E AudioRecord: AudioFlinger could not create record track, status: -1
04-10 23:17:45.114 21989 22017 E AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
04-10 23:17:45.114 21989 22017 E android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
04-10 23:17:45.114 21989 22017 I OF      : sound input setup with buffersize: 3552
04-10 23:17:45.119 21989 22027 I OF      : no audio input
```

**Comment by nishimotz** [comment]
Tested with v0.10.0RC3 and the situation is not changed.

To verify the recording permission issue #5736, I have modified the ofApp.cpp as follows to disable input stream, i.e. only using output stream.

```
$ diff src_org/ofApp.cpp src/ofApp.cpp
18c18
<       soundStream.setup(this,2,2, sampleRate,256, 4);
---
>       soundStream.setup(this,2,0, sampleRate,256, 4);
```

With v0.9.8, when touched on the device screen, upper wave shape moves, and the sound is played as expected.
With 0.10.0RC3, nothing works.

**Comment by arturoc** [comment]
Just tested this and i think you are correct, there seems to be 2 problems, one with permissions and the other with the soudn api we use being deprecated in android 25 and not working. To make it work we would need to use the native api for sound which is pretty low level, i have something working from a project i did a long time ago but it wasn't 100% stable

The other solution would be to roll back to android 19 or whatever we where using before which if i understand correctly would solve both this issues.

ping @HalfdanJ

**Comment by HalfdanJ** [comment]
Ahh. The permissions should be an easy fix, but the other issue I agree could sounds like it's a tougher issue. I unfortunately don't have time the coming 2 weeks to look at this due to a deadline. 

I'm wondering if there is a compromise by instead only upgrading to SDK 24? The primary reason I wanted to update was to be able to support ARCore which is personally the primary thing I use openFrameworks on Android for. But we need to get sound to work of course.

**Comment by arturoc** [comment]
i'll try 24 next week, could it be possible to only downgrade this particular example in the manifest and leave the rest at 25? or perhaps downgrade everything back to 19 and add a short AR example using 25 by now?

**Comment by arturoc** [comment]
this should be fixed now, i was getting a deprecated message cause we use some old calls to create the audio objects but it still works anyway. the problem was in the c++ side not using the new audio api in OF

**Comment by nishimotz** [comment]
Confirmed androidAudioExample of of_v20180430_android_release works as expected.
