### ISSUE TITLE
Emscripten full screen and antialiasing of 2d-shapes do not work anymore

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#6758]
I get this message when i press full screen:
```
Uncaught TypeError: Module.requestFullScreen is not a function
    at HTMLInputElement.onclick ((index):1)
```
And the circle isnt antialiased, while it is when I compile for desktop. And both were working with Emscripten before (I guess until OF 0.11.0). Here for example works both: https://arturocastro.net/files/of-emscripten/polygonExample/
And here not (my example - but it seems the same for the other examples): http://puredatagui.handmadeproductions.de/
Antialiasing fonts does work now, after I made this change: https://github.com/openframeworks/openFrameworks/issues/6745
Tested with OF 0.11.2 / Emscripten 1.40.1 / Ubuntu 20.04

**Comment by Jonathhhan** [comment]
Maybe the full screen issue is related to that: https://github.com/OGRECave/ogre/pull/1698

**Comment by Jonathhhan** [comment]
Regarding the fullscreen issue (not sure if it is helpful): If I use Module.requestFullscreen with a lower case "s" I can enter a black fullscreen without an error message, but if I switch back the Webassembly canvas is gone (or minimized to the size 0x0).
https://github.com/emscripten-core/emscripten/pull/4318

**Comment by ofTheo** [comment]
Thank you for digging into this.

I added this to our 0.12.0 tracking issue. 
If you find solutions to either feel free to submit a PR. :)

**Comment by ofTheo** [comment]
[From the forum](https://forum.openframeworks.cc/t/the-future-of-emscripten-and-of/38360/3) this works for me for the fullscreen issue:
```<input type="button" value="Fullscreen" onclick="Module['canvas'].requestFullscreen()">```

I can toggle back and forth and things work as expected.

**Comment by Jonathhhan** [comment]
Now it works also without -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0
Changed this in https://github.com/Jonathhhan/openFrameworks/blob/master/addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp:
```
    emscripten_set_keydown_callback("#canvas",this,1,&keydown_cb);
    emscripten_set_keyup_callback("#canvas",this,1,&keyup_cb);
    emscripten_set_mousedown_callback("#canvas",this,1,&mousedown_cb);
    emscripten_set_mouseup_callback("#canvas",this,1,&mouseup_cb);
    emscripten_set_mousemove_callback("#canvas",this,1,&mousemoved_cb);

    emscripten_set_touchstart_callback("#canvas",this,1,&touch_cb);
    emscripten_set_touchend_callback("#canvas",this,1,&touch_cb);
    emscripten_set_touchmove_callback("#canvas",this,1,&touch_cb);
    emscripten_set_touchcancel_callback("#canvas",this,1,&touch_cb);
```
And and replaced canvasX / canvasY with targetX / targetY.

Only thing for now that the recalculation of the mouse value in fullscreen mode still happens (with my edit) in https://github.com/emscripten-core/emscripten/blob/main/src/library_html5.js not sure how I can get the css canvas size into Open Frameworks.

The other big issue (maybe more an improvement) is, that it would be really great, if audio could run in a seperate JS thread for reducing latency and audio artifacts. Like with audioworkletprocessor https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor and not with ScriptProcessorNode https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode. Maybe also pthreads https://emscripten.org/docs/porting/pthreads.html could be a solution? I think I understand the basic concept of audioworkletprocessor, but I dont know how to pass the wasm module (already tried a few things without much success). Also not sure if the bottleneck is somewhere else, but I guess its the fact that everything happens in the main JS thread. Anyhow, with a buffersize of 4096 audio is quite stable right now, but with a lower buffer size it depends on the browser and the CPU/GPU.

**Comment by Jonathhhan** [comment]
changing this:
```
EGLint contextAttribs[] = { EGL_CONTEXT_MAJOR_VERSION, 3, EGL_NONE, EGL_NONE };
	std::vector <EGLint> attribList =
	   {
		   EGL_RED_SIZE, EGL_DONT_CARE,
		   EGL_GREEN_SIZE, EGL_DONT_CARE,
		   EGL_BLUE_SIZE, EGL_DONT_CARE,
		   EGL_ALPHA_SIZE, EGL_DONT_CARE,
		   EGL_DEPTH_SIZE, EGL_DONT_CARE,
		   EGL_STENCIL_SIZE, EGL_DONT_CARE,
		   EGL_SAMPLE_BUFFERS, EGL_DONT_CARE,
		   EGL_RENDERABLE_TYPE, EGL_OPENGL_ES3_BIT_KHR,
		   EGL_NONE
	   };
```
in https://github.com/Jonathhhan/openFrameworks/blob/master/addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp and adding the flag  -s USE_WEBGL2=1 to config.emscripten.default.mk enables webgl2 without editing any Emscripten file.

**Comment by Jonathhhan** [comment]
@ofTheo thank you very much for your help. I would say that basically this issues (and some others) are solved. Only the question how to implement the solutions in the best way for the pull requests (hard for me to judge, because I am really not a experienced c++ programmer). 
Last two Emscripten related issues (that I have in mind): Update OF for the current Emscripten version and make audio run in a seperate thread (or reduce latency / artifacts in another way).

**Comment by ofTheo** [comment]
Thanks @Jonathhhan !
This is all immensely helpful. 

I will probably pull in everything from your PR and maybe do a bit of cleanup and small fixes to make it more modular as you suggested. 

I can change the workflows now to use 2.0.6 and we can change the site docs to suggest that version too. 
Does 2.0.6 work just as well with the current release of OF? 

Thanks!!

**Comment by Jonathhhan** [comment]
Is it possible to use std::filesystem instead of boost::filesystem with Emscripten somehow? That would be great, because if I compile with -std=c++17 the .wasm file size is much smaller (around 20% from to the old size). And everything works if I compile without USE_PTHREADS=1 except the filesystem (but it compiles without errors). This is the JS error message:
`segmentation fault loading 4 bytes from address 0
printErr @ soundPlayerExample.html:1
soundPlayerExample.html:1 RuntimeError: abort(segmentation fault loading 4 bytes from address 0) at Error
    at jsStackTrace (soundPlayerExample.js:1:35326)
    at stackTrace (soundPlayerExample.js:1:35502)
    at abort (soundPlayerExample.js:1:30803)
    at SAFE_HEAP_LOAD (soundPlayerExample.js:1:19458)
    at Object.get (soundPlayerExample.js:1:103737)
    at ___sys_open (soundPlayerExample.js:1:106423)
    at realpath (soundPlayerExample.wasm:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (soundPlayerExample.wasm:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (soundPlayerExample.wasm:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0x488c9)
printErr @ soundPlayerExample.html:1
soundPlayerExample.html:1 exception thrown: RuntimeError: abort(RuntimeError: abort(segmentation fault loading 4 bytes from address 0) at Error
    at jsStackTrace (http://localhost:6931/soundPlayerExample.js:1:35326)
    at stackTrace (http://localhost:6931/soundPlayerExample.js:1:35502)
    at abort (http://localhost:6931/soundPlayerExample.js:1:30803)
    at SAFE_HEAP_LOAD (http://localhost:6931/soundPlayerExample.js:1:19458)
    at Object.get (http://localhost:6931/soundPlayerExample.js:1:103737)
    at ___sys_open (http://localhost:6931/soundPlayerExample.js:1:106423)
    at realpath (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8479]:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8484]:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (http://localhost:6931/soundPlayerExample.wasm:wasm-function[988]:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[989]:0x488c9)) at Error
    at jsStackTrace (http://localhost:6931/soundPlayerExample.js:1:35326)
    at stackTrace (http://localhost:6931/soundPlayerExample.js:1:35502)
    at abort (http://localhost:6931/soundPlayerExample.js:1:30803)
    at ___sys_open (http://localhost:6931/soundPlayerExample.js:1:106553)
    at realpath (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8479]:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8484]:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (http://localhost:6931/soundPlayerExample.wasm:wasm-function[988]:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[989]:0x488c9)
    at ofxEmscriptenSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[306]:0xc168)
    at ofSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[3034]:0x8a316),RuntimeError: abort(RuntimeError: abort(segmentation fault loading 4 bytes from address 0) at Error
    at jsStackTrace (http://localhost:6931/soundPlayerExample.js:1:35326)
    at stackTrace (http://localhost:6931/soundPlayerExample.js:1:35502)
    at abort (http://localhost:6931/soundPlayerExample.js:1:30803)
    at SAFE_HEAP_LOAD (http://localhost:6931/soundPlayerExample.js:1:19458)
    at Object.get (http://localhost:6931/soundPlayerExample.js:1:103737)
    at ___sys_open (http://localhost:6931/soundPlayerExample.js:1:106423)
    at realpath (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8479]:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8484]:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (http://localhost:6931/soundPlayerExample.wasm:wasm-function[988]:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[989]:0x488c9)) at Error
    at jsStackTrace (http://localhost:6931/soundPlayerExample.js:1:35326)
    at stackTrace (http://localhost:6931/soundPlayerExample.js:1:35502)
    at abort (http://localhost:6931/soundPlayerExample.js:1:30803)
    at ___sys_open (http://localhost:6931/soundPlayerExample.js:1:106553)
    at realpath (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8479]:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8484]:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (http://localhost:6931/soundPlayerExample.wasm:wasm-function[988]:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[989]:0x488c9)
    at ofxEmscriptenSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[306]:0xc168)
    at ofSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[3034]:0x8a316)
    at abort (http://localhost:6931/soundPlayerExample.js:1:30834)
    at ___sys_open (http://localhost:6931/soundPlayerExample.js:1:106553)
    at realpath (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8479]:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[8484]:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (http://localhost:6931/soundPlayerExample.wasm:wasm-function[988]:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[989]:0x488c9)
    at ofxEmscriptenSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[306]:0xc168)
    at ofSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[3034]:0x8a316)
    at ofApp::setup() (http://localhost:6931/soundPlayerExample.wasm:wasm-function[208]:0x7583)
    at ofNode::onParentOrientationChanged(glm::qua<float, (glm::qualifier)0>&) (http://localhost:6931/soundPlayerExample.wasm:wasm-function[624]:0x313c0)
printErr @ soundPlayerExample.html:1
soundPlayerExample.js:1 Uncaught RuntimeError: abort(RuntimeError: abort(segmentation fault loading 4 bytes from address 0) at Error
    at jsStackTrace (soundPlayerExample.js:1:35326)
    at stackTrace (soundPlayerExample.js:1:35502)
    at abort (soundPlayerExample.js:1:30803)
    at SAFE_HEAP_LOAD (soundPlayerExample.js:1:19458)
    at Object.get (soundPlayerExample.js:1:103737)
    at ___sys_open (soundPlayerExample.js:1:106423)
    at realpath (soundPlayerExample.wasm:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (soundPlayerExample.wasm:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (soundPlayerExample.wasm:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0x488c9)) at Error
    at jsStackTrace (soundPlayerExample.js:1:35326)
    at stackTrace (soundPlayerExample.js:1:35502)
    at abort (soundPlayerExample.js:1:30803)
    at ___sys_open (soundPlayerExample.js:1:106553)
    at realpath (soundPlayerExample.wasm:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (soundPlayerExample.wasm:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (soundPlayerExample.wasm:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0x488c9)
    at ofxEmscriptenSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0xc168)
    at ofSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0x8a316)
    at abort (soundPlayerExample.js:1:30834)
    at ___sys_open (soundPlayerExample.js:1:106553)
    at realpath (soundPlayerExample.wasm:0x3c043f)
    at std::__2::__fs::filesystem::__canonical(std::__2::__fs::filesystem::path const&, std::__2::error_code*) (soundPlayerExample.wasm:0x3c069c)
    at (anonymous namespace)::dataPathRoot() (soundPlayerExample.wasm:0x4870b)
    at ofToDataPath(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0x488c9)
    at ofxEmscriptenSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0xc168)
    at ofSoundPlayer::load(std::__2::__fs::filesystem::path const&, bool) (soundPlayerExample.wasm:0x8a316)
    at ofApp::setup() (soundPlayerExample.wasm:0x7583)
    at ofNode::onParentOrientationChanged(glm::qua<float, (glm::qualifier)0>&) (soundPlayerExample.wasm:0x313c0)
stdio.html:1 `
