### ISSUE TITLE
emscripten issue on runtime - Failed to load 'http://localhost:6931/stdio.html'.

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#8227]
```
Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:6931/stdio.html'.
```

After all the other svg / libfmt / texture issues are fixed, I get the above message. 
Wonder if it's related to cross domain?  or if there is a way to disable?

@Jonathhhan - any idea what this could be related to?

**Comment by ofTheo** [comment]
I see some discussion here: 
#8067 which is connected to this issue:

https://github.com/emscripten-core/emscripten/issues/14128

**Comment by danoli3** [comment]
Check my PR for emscripten it had a fix and readme changes for this. Maybe
merge

**Comment by Jonathhhan** [comment]
> ```
> Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:6931/stdio.html'.
> ```
> 
> After all the other svg / libfmt / texture issues are fixed, I get the above message. Wonder if it's related to cross domain? or if there is a way to disable?
> 
> @Jonathhhan - any idea what this could be related to?
@ofTheo Hello.
Sorry, no idea.
This is the error mesage I get with latest Emscripten and latest OF. Same as yours:
```
TypeError: Cannot read properties of undefined (reading 'getParameter')
    at _glGetString (index.js:1:147151)
    at index.wasm.ofGLESVersionFromGL(:6931/) (http://localhost:6931/index.wasm)
    at index.wasm.ofTexture::ofTexture(:6931/) (http://localhost:6931/index.wasm)
    at index.wasm.__wasm_call_ctors (index.wasm:0x14614e)
    at callRuntimeCallbacks (index.js:1:13435)
    at initRuntime (index.js:1:8825)
    at doRun (index.js:1:175387)
    at index.js:1:175599
```
https://github.com/openframeworks/openFrameworks/issues/8211#issuecomment-2525390083

**Comment by Jonathhhan** [comment]
Actually I get the same error after getting rid of the error above:
```
Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:6931/stdio.html'.
    at postExit (http://localhost:6931/index.js:7498:12)
    at http://localhost:6931/index.js:7525:11
    at callRuntimeCallbacks (http://localhost:6931/index.js:523:22)
    at exitRuntime (http://localhost:6931/index.js:348:3)
    at exitJS (http://localhost:6931/index.js:4354:5)
    at callMain (http://localhost:6931/index.js:7441:5)
    at doRun (http://localhost:6931/index.js:7466:7)
    at http://localhost:6931/index.js:7473:7
```
I can only say, that stdio.html seems to be part of emrun:
https://github.com/emscripten-core/emscripten/issues/19776

**Comment by dimitre** [comment]
I'm seeing the next set of errors in apothecary related to ofxOpenCv
sample:
```
em++: warning: DEMANGLE_SUPPORT is deprecated (mangled names no longer appear in stack traces). Please open a bug if you have a continuing need for this setting [-Wdeprecated]
wasm-ld: error: ../../../addons/obj/emscripten/Debug/ofxOpenCv/src/ofxCvFloatImage.o: undefined symbol: cv::cvarrToMat(void const*, bool, bool, int, cv::AutoBuffer<double, 136ul>*)
wasm-ld: error: ../../../addons/obj/emscripten/Debug/ofxOpenCv/src/ofxCvFloatImage.o: undefined symbol: cv::cvarrToMat(void const*, bool, bool, int, cv::AutoBuffer<double, 136ul>*)
wasm-ld: error: ../../../addons/obj/emscripten/Debug/ofxOpenCv/src/ofxCvGrayscaleImage.o: undefined symbol: cvCreateMat
wasm-ld: error: 
```

all errors:
https://github.com/openframeworks/openFrameworks/actions/runs/12218984776/job/34103250334

**Comment by ofTheo** [comment]
@danoli3 's PR here:
https://github.com/openframeworks/openFrameworks/pull/8056/files#diff-72fc26bdf138ea24982242c87d1abd9f91b8896bbf88f1208ce5df6ad43607beR102

I tried adding 
`-s NO_EXIT_RUNTIME=1` 

but I still get the error

**Comment by danoli3** [comment]
I'll check it out again, it was close last time it did work at some point was running so much faster to. 

I think the last commit on that PR I still had some issues to fix. 
Let me have a look, feeling code like today

**Comment by danoli3** [comment]
for ref a backup make that might have worked in July:
```
PLATFORM_LDFLAGS = -Wl --gc-sections --preload-file bin/data@data --emrun --bind --profiling-funcs -s USE_WEBGPU=1 -s WASM=1
PLATFORM_LDFLAGS += -s MAX_WEBGL_VERSION=2 -s WEBGL2_BACKWARDS_COMPATIBILITY_EMULATION=1 -s FULL_ES2 -s FULL_ES3=1 
PLATFORM_LDFLAGS += -s AUTO_NATIVE_LIBRARIES=1 -s AUTO_JS_LIBRARIES=1 -s EVAL_CTORS=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s LINKABLE
PLATFORM_LDFLAGS +=  $(PLATFORM_PTHREAD) -s PTHREAD_POOL_SIZE=4
PLATFORM_LDFLAGS += -s PROXY_TO_PTHREAD=1
# PLATFORM_LDFLAGS += -sEXPORTED_FUNCTIONS=_main
# PLATFORM_LDFLAGS += -s WASM_WORKERS=1 -s ENVIRONMENT="web,worker"
# PLATFORM_LDFLAGS += -s USE_GLFW=3 -lglfw
PLATFORM_LDFLAGS += --js-library $(OF_ADDONS_PATH)/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js
PLATFORM_LDFLAGS += --js-library $(OF_ADDONS_PATH)/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js






# 2 
#--export=__cpp_exception 
PLATFORM_LDFLAGS += --preload-file bin/data@data --emrun --bind --profiling-funcs -s USE_WEBGPU=1 -s WASM=1 
PLATFORM_LDFLAGS += -sMIN_WEBGL_VERSION=2 -s USE_WEBGL2=1 -s MAX_WEBGL_VERSION=2  -s FULL_ES2
#PLATFORM_LDFLAGS += -fwasm-exceptions 
PLATFORM_LDFLAGS += -s MINIFY_HTML=0
#PLATFORM_LDFLAGS += -s FILESYSTEM=1 
#-sFORCE_FILESYSTEM=1
PLATFORM_LDFLAGS +=  -sEXPORT_ALL=1
PLATFORM_LDFLAGS +=  -sEXPORT_KEEPALIVE=1
#PLATFORM_LDFLAGS += -s IGNORE_MISSING_MAIN=0  #-s SUPPORT_LONGJMP=wasm 
# PLATFORM_LDFLAGS += -lGL -lhtml5 -lopenal
PLATFORM_LDFLAGS += -s STANDALONE_WASM=1
PLATFORM_LDFLAGS += -s WEBGL2_BACKWARDS_COMPATIBILITY_EMULATION=1
PLATFORM_LDFLAGS += -s FULL_ES3=1
PLATFORM_LDFLAGS += -s AUTO_NATIVE_LIBRARIES=1 -s AUTO_JS_LIBRARIES=1 -s EVAL_CTORS=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1
#-sEXCEPTION_CATCHING_ALLOWED=[compile+link] -s EXPORT_EXCEPTION_HANDLING_HELPERS=1 -s EXCEPTION_STACK_TRACES=0
#PLATFORM_LDFLAGS += -s MALLOC=emmalloc
#PLATFORM_LDFLAGS += -sOFFSCREEN_FRAMEBUFFER=1
PLATFORM_LDFLAGS += $(PLATFORM_PTHREAD) -s PTHREAD_POOL_SIZE=4
PLATFORM_LDFLAGS += -sINITIAL_MEMORY=256mb -sSTACK_SIZE=64MB -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,ENV
#PLATFORM_LDFLAGS += -s NO_EXIT_RUNTIME=1
PLATFORM_LDFLAGS += -s VERBOSE=1 

PLATFORM_LDFLAGS += -s EXPORTED_FUNCTIONS="['_main']"
# PLATFORM_LDFLAGS += -s WASM_WORKERS=1 -s ENVIRONMENT="web,worker,node"
PLATFORM_LDFLAGS += -s AUDIO_WORKLET=1

# PLATFORM_LDFLAGS += -s USE_GLFW=3 -lglfw
PLATFORM_LDFLAGS += --js-library $(OF_ADDONS_PATH)/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js
PLATFORM_LDFLAGS += --js-library $(OF_ADDONS_PATH)/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js

ifdef PROJECT_EMSCRIPTEN_TEMPLATE
	PLATFORM_LDFLAGS += --shell-file $(PROJECT_EMSCRIPTEN_TEMPLATE)
#  else
#  	PLATFORM_LDFLAGS += --shell-file $(OF_LIBS_PATH)/openFrameworksCompiled/project/emscripten/template.html
endif

PLATFORM_OPTIMIZATION_LDFLAGS_RELEASE = -O0  -s VERBOSE=1 -s GL_ASSERTIONS=1 -s ASSERTIONS=1  -gsource-map -s TOTAL_MEMORY=$(PLATFORM_EMSCRIPTEN_TOTAL_MEMORY) -s ALLOW_MEMORY_GROWTH=1

PLATFORM_OPTIMIZATION_LDFLAGS_DEBUG = -O0 -g -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=536870912 							
PLATFORM_OPTIMIZATION_LDFLAGS_DEBUG += -fPIC -s VERBOSE=1 -s GL_ASSERTIONS=1 -s ASSERTIONS=1 
```

**Comment by danoli3** [comment]
This is all working now just CSP changes required

**Comment by ofTheo** [comment]
Awesome!  When you say working, do you mean you can call emrun and it loads without the stdio error? 

The goal is that people should be able to run locally without setting up any cors stuff etc.

**Comment by danoli3** [comment]
<img width="831" alt="image" src="https://github.com/user-attachments/assets/c08202c9-8b8f-4fcb-b1df-cb0d1ada4f33">

Yeah it even happens locally (thats localhost). Web got real strict ! 

Solutions: split: Style / script and auto gen index.js. Fixes a lot of the issues.
Then some use of SetTimeout in the core emscripten code which is still problematic 

Solution to nonce or hash the file to htaccess we generate. Counter dem hackers hey

**Comment by ofTheo** [comment]
@danoli3 thanks! 

I think the goal should be that users can at the least to  `emrun bin/em/3DPrimitivesExample/`  and it just works without needing to setup a local server or anything. 

It was until recently, so I am not sure if this is a recent emscripten change or something at the browser level. I Haven't seen any CSP errors but also haven't got past the stdio.html error. 

Are you able to push the changes for the `stdio.html`  error?

**Comment by ofTheo** [comment]
Following up on this, it looks like emscripten newer the 3.1.60 has the issues with stdio.html 

I think until we can find a solution we should revert apothecary runner and OF/OF to 3.1.50 which has been confirmed to work and then point people to 3.1.50 in the setup guides. 

I see this PR was merged, but the emrun / stdio issue was mentioned about not being resolved. 
https://github.com/openframeworks/openFrameworks/pull/8067

@danoli3 I tried the above LD flags and they didn't seem to make any difference to the error 
@Jonathhhan have you been able to get OF running on >= 3.1.65 locally without the emrun stdio error?

**Comment by danoli3** [comment]
It works without the error on the PR!

Just CSP stuff

**Comment by ofTheo** [comment]
Thanks @danoli3 
I pulled in your changes and tried them - no errors compiling but nothing on run, just hangs on download with no errors or warnings in Safari / Chrome / Firefox  

I think something else is broken in the nightly for emscripten aside from the CORS stuff etc 

Going to try an older ofxEmscriptenWindow 

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/3c9f113f-c9e6-4902-86ee-008f6c81a87d" />

**Comment by danoli3** [comment]
PLATFORM_LDFLAGS += -s ASSERTIONS=2
PLATFORM_LDFLAGS += -s GL_ASSERTIONS=1


Also we should implement this GLFW port for our uses:
https://github.com/pongasoft/emscripten-glfw

I had started to but got stuck in the mud with the libs

**Comment by danoli3** [comment]
```
index.js:770 wasm streaming compile failed: LinkError: WebAssembly.instantiate(): Import #42 "env" "__assert_fail": function import requires a callable
(anonymous) @ index.js:770Understand this errorAI
index.js:771 falling back to ArrayBuffer instantiation
(anonymous) @ index.js:771Understand this errorAI
index.js:737 failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): Import #42 "env" "__assert_fail": function import requires a callable
(anonymous) @ index.js:737Understand this errorAI
index.js:649 Aborted(LinkError: WebAssembly.instantiate(): Import #42 "env" "__assert_fail": function import requires a callable)
abort @ index.js:649Understand this errorAI
index.js:669 Uncaught (in promise) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #42 "env" "__assert_fail": function import requires a callable). Build with -sASSERTIONS for more info.
    at abort (index.js:669:11)
    at index.js:739:5Understand this errorAI
    ```

**Comment by danoli3** [comment]
Due to CSP block it seems

**Comment by danoli3** [comment]
Should be all resolved CSP, Library and with Sound Disabled works:
https://github.com/openframeworks/openFrameworks/pull/8253

**Comment by danoli3** [comment]
Yes this is all fixed and Emscripten 4.0.0 is targeted.
